#!/bin/bash
#
# Checks if two files, which contain unsorted lists, contain the same elements
#
# ./check_output.sh expected observed

if [[ $(grep -Fxv -f $1 $2 | wc -l) != "0" ]] || [[ $(wc -l $1 | awk '{print $1}') != $(wc -l $2 | awk '{print $1}') ]]; then
    echo "ERROR: Observed output does not match the expected output."
else
    echo "Test Passed!"
fi
