#!/bin/bash
#
# Wrapper script for running all pieces of the design algorithm.
#
# Usage: ./design_community.sh [-s] species_reactions_file substrates products
BIN_DIR=(BIN_DIR)
CBC_BIN=(CBC_BIN)
TMP_DIR=.
SIMPLE=false

# Parsing arguments
position_args=()
while [[ $# > 0 ]]
do
    key="$1"
    case $key in
		-s)
		SIMPLE=true
		;;
		-t)
		TMP_DIR=$2
		shift
		;;
		*)
		position_args+=($1)
		;;
    esac
shift
done

species_file_location=${position_args[0]}
species_file=$(basename $species_file_location)

if [ $SIMPLE = true ]; then
	$BIN_DIR/write_design_problem -s $species_file_location > ${TMP_DIR}/${species_file}.prob
else
	$BIN_DIR/write_design_problem $species_file_location > ${TMP_DIR}/${species_file}.prob
fi
$CBC_BIN -import ${TMP_DIR}/${species_file}.prob -branchAnd -solution ${TMP_DIR}/${species_file}.sol >&2
$BIN_DIR/get_solution_species ${TMP_DIR}/${species_file}.sol
rm ${TMP_DIR}/${species_file}.prob
rm ${TMP_DIR}/${species_file}.sol
