#!/bin/bash
#
# Wrapper script for running all pieces of the design algorithm.
#
# Usage: ./design_community.sh [-s] species_reactions_file substrates products
BIN_DIR=(BIN_DIR)
CBC_BIN=(CBC_BIN)
TMP_DIR=.

# Parsing arguments
position_args=()
all_args=""
while [[ $# > 0 ]]
do
    key="$1"
    case $key in
		-s)
		all_args="$all_args $1"
		;;
		-srd)
		all_args="$all_args $1 $2"
		shift
		;;
		-rd)
		all_args="$all_args $1 $2"
		shift
		;;
		-spd)
		all_args="$all_args $1 $2"
		shift
		;;
		-md)
		all_args="$all_args $1 $2"
		shift
		;;
		-t)
		TMP_DIR=$2
		shift
		;;
		*)
		position_args+=($1)
		all_args="$all_args $1"
		;;
    esac
shift
done

problem_definition_file_location=${position_args[0]}
problem_definition_file=$(basename $problem_definition_file_location)

$BIN_DIR/write_design_problem $all_args > ${TMP_DIR}/${problem_definition_file}.prob
$CBC_BIN -import ${TMP_DIR}/${problem_definition_file}.prob -branchAnd -solution ${TMP_DIR}/${problem_definition_file}.sol >&2
$BIN_DIR/get_solution_species ${TMP_DIR}/${problem_definition_file}.sol
rm ${TMP_DIR}/${problem_definition_file}.prob
rm ${TMP_DIR}/${problem_definition_file}.sol
